name: first-workflow
on: [push]
# push 했을 때 jobs가 움직인다.
jobs:
  shell-cmd-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello
        run: echo "Hello World2"
      - name: multiple line cmd
        run: |
          node -v
          npm -v